<a href="https://colab.research.google.com/github/monikakote/Numpy/blob/main/Arithmetic_Operations_Part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arithmetic Operations in NumPy Arrays

a+b : np.add(a,b)

a-b : np.substract(a,b)

a*b : np.multiply(a,b)

a/b : np.divide(a,b)

a%b : np.mod(a,b)

a**b: np.power(a,b)

1/a : np.reciprocal(a)

# 1-D array

# 1. Add 5 to each element

In [1]:
import numpy as np
arr = np.array([10, 20, 30])
result = arr + 5
print(result)


[15 25 35]


# 2. Subtract 2 from each element

In [2]:
arr = np.array([5, 10, 15])
result = arr - 2
print(result)


[ 3  8 13]


# 3. Multiply each element by 4

In [3]:
arr = np.array([1, 2, 3])
result = arr * 4
print(result)


[ 4  8 12]


# 4. Divide each element by 2

In [4]:
arr = np.array([8, 16, 24])
result = arr / 2
print(result)


[ 4.  8. 12.]


# 5. Modulo with 4

In [5]:
arr = np.array([9, 10, 11])
result = arr % 4
print(result)


[1 2 3]


# 6. Power of 2

In [6]:
arr = np.array([2, 3, 4])
result = arr ** 2
print(result)


[ 4  9 16]


# 7. Reciprocal (1/x)

In [7]:
arr = np.array([1, 2, 4])
result = np.reciprocal(arr)
print(result)


[1 0 0]


# 2-D array

In [8]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 3]])
print("a * b:\n", a * b)


a * b:
 [[ 2  0]
 [ 3 12]]


# Arithmetic Functions

np.min(x)

np.max(x)

np.argmin(x)

np.sqrt(x)

np.sin(x)

np.cos(x)

np.cumsum(x)

# 1. np.min(x), np.max(x), np.argmin(x), np.argmax(x)

In [9]:
arr = np.array([10, 25, 5, 40])
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Min Index:", np.argmin(arr))
print("Max Index:", np.argmax(arr))


Min: 5
Max: 40
Min Index: 2
Max Index: 3


# 2. np.sqrt(x)

In [10]:
arr = np.array([4, 9, 16])
print("Square Roots:", np.sqrt(arr))


Square Roots: [2. 3. 4.]


# 3. np.sin(x), np.cos(x)

In [11]:
arr = np.array([0, np.pi/2, np.pi])
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))


Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


# 4. np.cumsum(x)

In [12]:
arr = np.array([1, 2, 3, 4])
print("Cumulative Sum:", np.cumsum(arr))


Cumulative Sum: [ 1  3  6 10]


# 5. np.min(x, axis=0) and np.min(x, axis=1)

In [13]:
arr = np.array([[7, 8, 9], [3, 4, 5]])
print("Min in each row:", np.min(arr, axis=1))
print("Min in each column:", np.min(arr, axis=0))


Min in each row: [7 3]
Min in each column: [3 4 5]
