<a href="https://colab.research.google.com/github/monikakote/Numpy/blob/main/Broadcasting_in_NumPy_Part5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadcasting in NumPy

# Broadcasting Rules Recap

Two arrays can be broadcast together if:

Their dimensions are equal or

One of them is 1 in that dimension

# All Key Broadcasting Cases with Examples

# 1. Scalar with array

A scalar is broadcasted to match any array.

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = 10
print("a + b =", a + b)


a + b = [11 12 13]


# 2. Same 1D shape arrays

In [2]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print("a + b =", a + b)


a + b = [11 22 33]


# 3. Mismatched 1D arrays

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30])
print("a + b =", a + b)  # Error


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [4]:
import numpy as np

# Array with shape (3,1)
a = np.array([[10], [20], [30]])
print("a:\n", a)
print("Shape of a:", a.shape)
print()

# Array with shape (1,4)
b = np.array([[1, 2, 3, 4]])
print("b:\n", b)
print("Shape of b:", b.shape)
print()

# Broadcasting addition
result = a + b
print("a + b:\n", result)
print("Shape of result:", result.shape)


a:
 [[10]
 [20]
 [30]]
Shape of a: (3, 1)

b:
 [[1 2 3 4]]
Shape of b: (1, 4)

a + b:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Shape of result: (3, 4)
