<a href="https://colab.research.google.com/github/monikakote/Numpy/blob/main/creatingNumpyarry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating NumPy Arrays

To create a NumPy array , you can use the function np.array()

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr)


[10 20 30 40]


# Dimensions in Array

1-D Arrays

2-D Arrays

3-D Arrays

Higher Dimensional Arrays



In [3]:
#2D array
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)
print('Dimensions =', arr2.ndim)


[[1 2]
 [3 4]]
Dimensions = 2


In [4]:
#3D array
arr3 = np.array([[[1], [2]], [[3], [4]]])
print(arr3)
print('Dimensions =', arr3.ndim)


[[[1]
  [2]]

 [[3]
  [4]]]
Dimensions = 3


In [5]:
#10D array
arrn = np.array([1, 2], ndmin=10)
print(arrn)
print('Dimensions =', arrn.ndim)


[[[[[[[[[[1 2]]]]]]]]]]
Dimensions = 10


# Special NumPy Array

array filled with 0's

array filled with 1's

create an empty array

an array with a range of elements

array diagonal element filled with 1's

create a array with values that are spaced linearly in a specified interval

In [6]:
#Zeros
arr_zero = np.zeros((2, 2))
print(arr_zero)


[[0. 0.]
 [0. 0.]]


In [7]:
#Ones
arr_one = np.ones((2, 3), dtype=int)
print(arr_one)


[[1 1 1]
 [1 1 1]]


In [8]:
#Empty
arr_emp = np.empty((2, 3))
print(arr_emp)


[[8.39473080e-316 0.00000000e+000 6.91878117e-310]
 [6.91878117e-310 6.91876773e-310 5.33270743e-317]]


In [9]:
#Range
arr_rn = np.arange(10, 20, 2)
print(arr_rn)


[10 12 14 16 18]


In [10]:
#Diagonal
arr_dia = np.eye(4)
print(arr_dia)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# Linspace
arr_lin = np.linspace(0, 1, 4)
print(arr_lin)


[0.         0.33333333 0.66666667 1.        ]


# Create NumPy Arrays with Random Numbers

1. rand()

rand() : the function is used to generate a random number between 0 to 1

In [12]:
#rand()
rand_arr = np.random.rand(3, 2)
print(rand_arr)


[[0.53455372 0.6398835 ]
 [0.96561075 0.87258776]
 [0.58135834 0.97664693]]


# 2. randn()

randn() : the function is used to generate a random value cloase to zero. This may return positive or negative numbers as well.

In [13]:
#randn()
randn_arr = np.random.randn(2, 2)
print(randn_arr)


[[ 0.56737673 -2.03750476]
 [-0.53935291 -0.00784422]]


# 3. ranf()

ranf() : the function for doing random sampling in numpy . It returns an array of specified shape and fills it with random floats in the half open interval [0.0,1.0)

In [14]:
#ranf()
ranf_arr = np.random.ranf((2, 3))
print(ranf_arr)


[[0.12235988 0.51349383 0.51265226]
 [0.3160636  0.31673369 0.59512483]]


# 4. randint()

the function is used to generate a random number between a given range.

In [15]:
#randint()
randint_arr = np.random.randint(10, 50, size=(2, 4))
print(randint_arr)


[[43 11 18 20]
 [38 29 22 34]]
