<a href="https://colab.research.google.com/github/monikakote/Numpy/blob/main/Indexing_and_Slicing__Part6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1 Indexing in NumPy Arrays

In [1]:
import numpy as np

# 1D Array
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print("Element at index 2:", arr[2])
print("Element at index -2:", arr[-2])


[10 20 30 40 50]
Element at index 2: 30
Element at index -2: 40


# 2D Indexing (Matrix)

In [2]:
# 2D Array
mat = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])

print(mat)
print("Shape:", mat.shape)
print("Element at row 1, col 2:", mat[1, 2])
print("Element at row 2, col 0:", mat[2, 0])


[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Shape: (3, 3)
Element at row 1, col 2: 30
Element at row 2, col 0: 35


# 3D Indexing

In [3]:
# 3D Array: shape (1, 2, 3)
arr3d = np.array([[[100, 200, 300],
                   [400, 500, 600]]])

print(arr3d)
print("Dimension:", arr3d.ndim)
print("arr3d[0,0,1]:", arr3d[0,0,1])
print("arr3d[0,1,2]:", arr3d[0,1,2])


[[[100 200 300]
  [400 500 600]]]
Dimension: 3
arr3d[0,0,1]: 200
arr3d[0,1,2]: 600


# 2 Slicing in NumPy Arrays

In [5]:
a = np.array([5, 10, 15, 20, 25, 30])
print("Original array:", a)
print("From index 2 to 4:", a[2:5])
print("From index 3 to end:", a[3:])
print("Start to index 3:", a[:4])
print("Every second element:", a[::2])
print("Reverse array:", a[::-1])


Original array: [ 5 10 15 20 25 30]
From index 2 to 4: [15 20 25]
From index 3 to end: [20 25 30]
Start to index 3: [ 5 10 15 20]
Every second element: [ 5 15 25]
Reverse array: [30 25 20 15 10  5]


In [6]:
b = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])

print(b)
print("Second row (index 1):", b[1])
print("From 1st row, elements 1 to 3:", b[0, 1:4])
print("Rows 1 & 2, first two cols:\n", b[1:3, 0:2])


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Second row (index 1): [50 60 70 80]
From 1st row, elements 1 to 3: [20 30 40]
Rows 1 & 2, first two cols:
 [[ 50  60]
 [ 90 100]]
