<a href="https://colab.research.google.com/github/monikakote/Numpy/blob/main/Iterating_NumPy_Array_Part7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Iterating NumPy Array

# 1-D Array

In [1]:
import numpy as np

arr1D = np.array([10, 20, 30, 40])
print("1-D Array:")
print(arr1D)
print("\nIterating 1-D Array:")
for value in arr1D:
    print(value)


1-D Array:
[10 20 30 40]

Iterating 1-D Array:
10
20
30
40


# 2-D Array Iteration

In [2]:
arr2D = np.array([[11, 12, 13], [21, 22, 23]])
print("2-D Array:")
print(arr2D)

print("\nRow-wise Iteration:")
for row in arr2D:
    print(row)

print("\nElement-wise Iteration:")
for row in arr2D:
    for item in row:
        print(item)


2-D Array:
[[11 12 13]
 [21 22 23]]

Row-wise Iteration:
[11 12 13]
[21 22 23]

Element-wise Iteration:
11
12
13
21
22
23


# 3-D Array Iteration

In [3]:
arr3D = np.array([[[101, 102], [103, 104]], [[201, 202], [203, 204]]])
print("3-D Array:")
print(arr3D)

print("\nMatrix-wise Iteration:")
for matrix in arr3D:
    for row in matrix:
        print(row)

print("\nElement-wise Iteration using np.nditer:")
for value in np.nditer(arr3D):
    print(value)

print("\nUsing ndenumerate (with index):")
for index, value in np.ndenumerate(arr3D):
    print(index, value)


3-D Array:
[[[101 102]
  [103 104]]

 [[201 202]
  [203 204]]]

Matrix-wise Iteration:
[101 102]
[103 104]
[201 202]
[203 204]

Element-wise Iteration using np.nditer:
101
102
103
104
201
202
203
204

Using ndenumerate (with index):
(0, 0, 0) 101
(0, 0, 1) 102
(0, 1, 0) 103
(0, 1, 1) 104
(1, 0, 0) 201
(1, 0, 1) 202
(1, 1, 0) 203
(1, 1, 1) 204
