<a href="https://colab.research.google.com/github/monikakote/Numpy/blob/main/Part_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Functions In NumPy

# Arithmetic Functions

Shuffle

Unique

Resize

Flatten

Ravel

# Shuffle

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print('Before Shuffling :- ', arr)
np.random.shuffle(arr)
print('After Shuffling :- ', arr)


Before Shuffling :-  [10 20 30 40 50]
After Shuffling :-  [10 40 30 20 50]


# Unique

In [2]:
arr1 = np.array([3, 6, 3, 2, 9, 6, 1])
print('arr1 :- ', arr1)
x = np.unique(arr1)
y = np.unique(arr1, return_index=True, return_counts=True)
print('Unique values :- ', x)
print('Index values :- \n', y)


arr1 :-  [3 6 3 2 9 6 1]
Unique values :-  [1 2 3 6 9]
Index values :- 
 (array([1, 2, 3, 6, 9]), array([6, 3, 0, 1, 4]), array([1, 1, 2, 2, 1]))


# Resize

In [3]:
arr2 = np.array([11, 22, 33, 44])
print('Before', arr2)
z = np.resize(arr2, (2, 2))
print('resize\n', z)


Before [11 22 33 44]
resize
 [[11 22]
 [33 44]]


# Flatten and Ravel

Converts 2-D array into 1-D array

order : {'C','F','A','K'},Optional

'C' means to flatten in row-major (C-style) order

'F' means to flatten in column-major(Fortan-style)order

'A' means to flatten in column-major order if 'a' is Fortan contiguous in memory ,row-major order otherwise

'K' means to flatten 'a' in the order the elements occur in memory
The default is 'C'

In [4]:
arr3 = np.array([[9, 8], [7, 6], [5, 4]])
print('Output of arr3\n', arr3)
print()
print('Flatten output:-', arr3.flatten())
print()
print('Flatten order output:-', arr3.flatten(order='F'))
print()
print('Ravel', np.ravel(arr3, order='F'))


Output of arr3
 [[9 8]
 [7 6]
 [5 4]]

Flatten output:- [9 8 7 6 5 4]

Flatten order output:- [9 7 5 8 6 4]

Ravel [9 7 5 8 6 4]


# Insert and Delete Functions

# Insert

In [5]:
arr4 = np.array([9, 8, 7, 6])
print('arr4:- ', arr4)
i = np.insert(arr4, (1, 3), 99)
print(i)

arr5 = np.array([[5, 10, 15], [20, 25, 30]])
i1 = np.insert(arr5, 1, 50, axis=1)
i2 = np.insert(arr5, 1, 60, axis=0)
i3 = np.insert(arr5, 1, [70, 80], axis=1)
print('i1 \n', i1)
print()
print('i2 \n', i2)
print()
print('i3 \n', i3)


arr4:-  [9 8 7 6]
[ 9 99  8  7 99  6]
i1 
 [[ 5 50 10 15]
 [20 50 25 30]]

i2 
 [[ 5 10 15]
 [60 60 60]
 [20 25 30]]

i3 
 [[ 5 70 10 15]
 [20 80 25 30]]


# Append

In [6]:
arr6 = np.array([[2, 4, 6], [8, 10, 12]])
print('arr \n', arr6)
print('\nInserted \n')
x = np.append(arr6, [[14, 16, 18]], axis=0)
print(x)


arr 
 [[ 2  4  6]
 [ 8 10 12]]

Inserted 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Delete

In [7]:
arr7 = np.array([100, 200, 300, 400, 500])
print('arr:- ', arr7)
d = np.delete(arr7, 3)
print('After deleting:- ', d)


arr:-  [100 200 300 400 500]
After deleting:-  [100 200 300 500]
