<a href="https://colab.research.google.com/github/monikakote/Numpy/blob/main/Part_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Join and Split Functions in Numpy Array

Join Array :- Joining means putting contents of two or more arrays in a single array

# Join array

# Concatenate function

In [1]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

# concatenate function
result = np.concatenate((arr1, arr2))
print('Concatenate :-', result)


Concatenate :- [10 20 30 40 50 60]


# Stack Function

In [2]:
arr3 = np.array([100, 200, 300])
arr4 = np.array([400, 500, 600])

# Stack in different ways
stacked = np.stack((arr3, arr4), axis=1)
hstacked = np.hstack((arr3, arr4))  # horizontal
vstacked = np.vstack((arr3, arr4))  # vertical
dstacked = np.dstack((arr3, arr4))  # depth

print('Stack:\n', stacked)
print('\nHorizontal Stack:\n', hstacked)
print('\nVertical Stack:\n', vstacked)
print('\nDepth Stack:\n', dstacked)


Stack:
 [[100 400]
 [200 500]
 [300 600]]

Horizontal Stack:
 [100 200 300 400 500 600]

Vertical Stack:
 [[100 200 300]
 [400 500 600]]

Depth Stack:
 [[[100 400]
  [200 500]
  [300 600]]]


# Split Array

Split Array :- Splitting breaks one array into multiple

# Split 1-D Array

In [3]:
import numpy as np

arr = np.array([11, 22, 33, 44, 55, 66])
print('arr\n', arr)

split_arr = np.array_split(arr, 3)

print('\nSplit Array\n', split_arr)
print('\n1st Split Array:-', split_arr[0])
print('\nType of Result:', type(split_arr))


arr
 [11 22 33 44 55 66]

Split Array
 [array([11, 22]), array([33, 44]), array([55, 66])]

1st Split Array:- [11 22]

Type of Result: <class 'list'>


# Split 2-D Array

In [4]:
arr2d = np.array([[1, 3], [5, 7], [9, 11]])
print('arr2d\n', arr2d)

split_rows = np.array_split(arr2d, 2)
split_columns = np.array_split(arr2d, 2, axis=1)

print('\nSplit by Rows:\n', split_rows)
print('\nSplit by Columns:\n', split_columns)
print('\nType of Result:', type(split_rows))


arr2d
 [[ 1  3]
 [ 5  7]
 [ 9 11]]

Split by Rows:
 [array([[1, 3],
       [5, 7]]), array([[ 9, 11]])]

Split by Columns:
 [array([[1],
       [5],
       [9]]), array([[ 3],
       [ 7],
       [11]])]

Type of Result: <class 'list'>
