<a href="https://colab.research.google.com/github/monikakote/Numpy/blob/main/Part_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix in NumPy Arrays

In [1]:
import numpy as np
a = np.matrix([[2,4,6],[3,6,9]])
print('a\n',a)
print('Type:-',type(a))


a
 [[2 4 6]
 [3 6 9]]
Type:- <class 'numpy.matrix'>


# Matrix Addition and Multiplication

In [3]:
import numpy as np
x = np.matrix([[2,1],[0,1]])
y = np.matrix([[1,3],[4,2]])
print('x\n',x)
print('y\n',y)
print()
print('Addition:-\n',x + y)
print('Multiplication:-\n',x.dot(y))


x
 [[2 1]
 [0 1]]
y
 [[1 3]
 [4 2]]

Addition:-
 [[3 4]
 [4 3]]
Multiplication:-
 [[6 8]
 [4 2]]


# Matrix Function in NumPy Arrays

Transpose

Swapaxes

Inverse

Power

Determinant

# Transpose

In [4]:
import numpy as np
m = np.matrix([[2,5,7],[1,3,9]])
print('m\n',m)
print()
print('Transpose\n',np.transpose(m))
print('\n',m.T)


m
 [[2 5 7]
 [1 3 9]]

Transpose
 [[2 1]
 [5 3]
 [7 9]]

 [[2 1]
 [5 3]
 [7 9]]


# Swapaxes

In [5]:
m = np.matrix([[7,8,9],[4,5,6]])
print('m\n',m)
print('After Swapping')
print(np.swapaxes(m,0,1))


m
 [[7 8 9]
 [4 5 6]]
After Swapping
[[7 4]
 [8 5]
 [9 6]]


# Inverse

In [6]:
m3 = np.matrix([[5,2],[7,3]])
print('m3\n',m3)
print()
print('Inverse matrix \n')
print(np.linalg.inv(m3))


m3
 [[5 2]
 [7 3]]

Inverse matrix 

[[ 3. -2.]
 [-7.  5.]]


# Power

In [7]:
m4 = np.matrix([[2,1],[1,2]])
print('m4\n',m4)
print()
print(np.linalg.matrix_power(m4,2))
print()
print('identity Matrix')
print(np.linalg.matrix_power(m4,0))
print()
print('Inverse Matrix')
print(np.linalg.matrix_power(m4,-1))


m4
 [[2 1]
 [1 2]]

[[5 4]
 [4 5]]

identity Matrix
[[1 0]
 [0 1]]

Inverse Matrix
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]


# Determinant

In [8]:
m5 = np.matrix([[2,3,4],[1,0,2],[5,1,3]])
print('m5\n',m5)
print()
print('Determinant\n')
print(np.linalg.det(m5))


m5
 [[2 3 4]
 [1 0 2]
 [5 1 3]]

Determinant

21.0
