<a href="https://colab.research.google.com/github/monikakote/Numpy/blob/main/Shape_%26_Reshaping_Part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Shape & Reshaping in NumPy Arrays

# Shape

In [1]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original Array:")
print(arr)
print()
print("Shape of arr:", arr.shape)
print("Dimension:", arr.ndim)


Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Shape of arr: (3, 3)
Dimension: 2


# Reshape

In [2]:

data = np.array([100, 200, 300, 400, 500, 600])
print("Original 1D Array:")
print(data)
print("Dimension:", data.ndim)
print()

reshaped_2d = data.reshape(3, 2)
print("Reshaped to 2D (3x2):")
print(reshaped_2d)
print("Dimension:", reshaped_2d.ndim)
print()

reshaped_3d = data.reshape(1, 3, 2)
print("Reshaped to 3D (1x3x2):")
print(reshaped_3d)
print("Dimension:", reshaped_3d.ndim)
print()

flattened = reshaped_3d.reshape(-1)
print("Flattened back to 1D:")
print(flattened)
print("Dimension:", flattened.ndim)


Original 1D Array:
[100 200 300 400 500 600]
Dimension: 1

Reshaped to 2D (3x2):
[[100 200]
 [300 400]
 [500 600]]
Dimension: 2

Reshaped to 3D (1x3x2):
[[[100 200]
  [300 400]
  [500 600]]]
Dimension: 3

Flattened back to 1D:
[100 200 300 400 500 600]
Dimension: 1
